version: '3.8'
services:
  web:
    container_name: mern-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:5050
    networks:
      - mern-net

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-api
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    networks:
      - mern-net

  mongodb:
    image: mongo
    container_name: mern-db
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - mern-net

volumes:
  dbdata:

networks:
  mern-net:
    driver: bridge